controller_manager:
  ros__parameters:
      update_rate: 100
      use_sim_time: true

      effort_controller:
        type: effort_controllers/JointGroupEffortController

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

effort_controller:
  ros__parameters:
    publish_rate: 100

    base_frame_id: world

    joints:
      - platform
      - shoulder
      - elbow
      - wrist_revolute
      - wrist_bend
      - effector_revolute

joint_state_broadcaster:
  ros__parameters:
      interfaces:
        - position
        - velocity
      joints:
        - platform
        - shoulder
        - elbow
        - wrist_revolute
        - wrist_bend
        - effector_revolute
