speed:
  j_1:
    P: 40.0
    I: 5.0
    D: 0.0
    N: 0.0
    I_min: -0.1
    I_max: 0.1

  j_2:
    P: 40.0
    I: 5.0
    D: 0.0
    N: 0.0
    I_min: -0.4
    I_max: 0.4

  j_3:
    P: 40.0
    I: 5.0
    D: 0.0
    N: 0.0
    I_min: -1.4
    I_max: 1.4

  j_4:
    P: 30.0
    I: 3.0
    D: 0.0
    N: 0.0
    I_min: -15.0
    I_max: 15.0

  j_5:
    P: 30.0
    I: 3.0
    D: 0.0
    N: 0.0
    I_min: -15.0
    I_max: 15.0

  j_6:
    P: 60.0
    I: 10.0
    D: 0.0
    N: 0.0
    I_min: -0.1
    I_max: 0.1

position:
  j_1:
    P: 20.0
    I: 2.0
    D: 0.0
    N: 1.0
    I_min: -0.01
    I_max: 0.01

  j_2:
    P: 10.0
    I: 2.0
    D: 0.0
    N: 1.5
    I_min: -0.01
    I_max: 0.01

  j_3:
    P: 15.0
    I: 30.0
    D: 0.0
    N: 1.5
    I_min: -0.01
    I_max: 0.01

  j_4:
    P: 30.0
    I: 60.0
    D: 0.0
    N: 1.5
    I_min: -0.01
    I_max: 0.01

  j_5:
    P: 20.0
    I: 40.0
    D: 0.0
    N: 1.5
    I_min: -0.01
    I_max: 0.01

  j_6:
    P: 16.0
    I: 0.01
    D: 0.0
    N: 1.5
    I_min: -0.001
    I_max: 0.001