speed:
  j_1:
    P: 20.0
    I: 1.0
    D: 0.0
    N: 0.0
    I_min: -0.1
    I_max: 0.1

  j_2:
    P: 25.0
    I: 3.0
    D: 0.0
    N: 0.0
    I_min: -0.4
    I_max: 0.4

  j_3:
    P: 30.0
    I: 10.0
    D: 0.0
    N: 0.0
    I_min: -1.0
    I_max: 1.0

  j_4:
    P: 60.0
    I: 10.0
    D: 0.0
    N: 0.0
    I_min: -3.0
    I_max: 3.0

  j_5:
    P: 50.0
    I: 30.0
    D: 0.0
    N: 0.0
    I_min: -1.0
    I_max: 1.0

  j_6:
    P: 60.0
    I: 10.0
    D: 0.0
    N: 0.0
    I_min: -0.1
    I_max: 0.1

position:
  j_1:
    P: 1.5
    I: 0.0
    D: 0.0
    N: 1.0
    I_min: -0.0
    I_max: 0.0

  j_2:
    P: 2.0
    I: 0.01
    D: 0.0
    N: 1.5
    I_min: -0.005
    I_max: 0.005

  j_3:
    P: 2.0
    I: 0.01
    D: 0.0
    N: 1.5
    I_min: -0.001
    I_max: 0.001

  j_4:
    P: 4.0
    I: 0.01
    D: 0.0
    N: 1.5
    I_min: -0.001
    I_max: 0.001

  j_5:
    P: 4.0
    I: 0.01
    D: 0.0
    N: 1.5
    I_min: -0.001
    I_max: 0.001

  j_6:
    P: 16.0
    I: 0.01
    D: 0.0
    N: 1.5
    I_min: -0.001
    I_max: 0.001