speed:
  j_1:
    P: 2000.0
    I: 100.0
    D: 50.0
    N: 1.0

  j_2:
    P: 75.0
    I: 0.1
    D: 20.0
    N: 0.1

  j_3:
    P: 10.0
    I: 0.00
    D: 10.0
    N: 0.1

  j_4:
    P: 2.0
    I: 0.0
    D: 0.0
    N: 0.0

  j_5:
    P: 5.0
    I: 0.05
    D: 25.0
    N: 0.5

  j_6:
    P: 0.05
    I: 0.0
    D: 0.0
    N: 0.0

position:
     