speed:
  j_1:
    P: 20.0
    I: 30.0
    D: 0.0
    N: 0.0
    I_min: -0.005
    I_max: 0.005

  j_2:
    P: 40.0
    I: 10.0
    D: 0.0
    N: 0.0
    I_min: -100.0
    I_max: 100.0

  j_3:
    P: 20.0
    I: 8.
    D: 0.0
    N: 0.0
    I_min: -20.0
    I_max: 20.0

  j_4:
    P: 0.75
    I: 0.5
    D: 0.0
    N: 0.0
    I_min: -2.0
    I_max: 2.0

  j_5:
    P: 0.5
    I: 0.15
    D: 0.0
    N: 0.0
    I_min: -0.5
    I_max: 0.5

  j_6:
    P: 0.0
    I: 0.0
    D: 0.0
    N: 0.0
    I_min: -0.0
    I_max: 0.0

position:
  j_1:
    P: 5.0
    I: 0.0
    D: 0.0
    N: 1.0
    I_min: -0.0
    I_max: 0.0

  j_2:
    P: 2.0
    I: 0.01
    D: 0.0
    N: 1.5
    I_min: -0.005
    I_max: 0.005

  j_3:
    P: 2.0
    I: 0.01
    D: 0.0
    N: 1.5
    I_min: -0.001
    I_max: 0.001

  j_4:
    P: 4.0
    I: 0.01
    D: 0.0
    N: 1.5
    I_min: -0.001
    I_max: 0.001

  j_5:
    P: 4.0
    I: 0.01
    D: 0.0
    N: 1.5
    I_min: -0.001
    I_max: 0.001

  j_6:
    P: 0.0
    I: 0.0
    D: 0.0
    N: 1.5
    I_min: -0.0
    I_max: 0.0